### PR TITLE
Prevent npe if lure tree recipe doesn't exist

### PR DESCRIPTION
**Pull request by democat3457**

### CODE REVIEW

**Comment by DaedalusGame** [comment]
this literally should error

**Comment by democat3457** [comment]
what should error

**Comment by DaedalusGame** [comment]
if you try to remove a luretree food that doesn't exist in the first place the game should yell at you for that

**Comment by democat3457** [comment]
well that didnt happen

[crash-2021-04-14_17.41.15-client.txt](https://github.com/DaedalusGame/BetterWithAddons/files/6314565/crash-2021-04-14_17.41.15-client.txt)

**Comment by DaedalusGame** [comment]
oh yeah, this shouldn't actually resolve the recipe in the constructor, that's a bug, the recipe needs to be resolved in apply- otherwise you'd only be able to remove recipes that are added before crafttweaker runs its scripts.

**Comment by democat3457** [comment]
how about now

**Pull request merged**
